backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'select',
          multiple: 'true',
          options:
            [
              'scotch',
              'irish',
              'australian',
              'japanese',
              'bourbon',
              '10 year',
              '12 year',
              '15 year',
              '21 year',
              '17 year',
              'sherry cask',
              'port cask',
              'peated',
              'sweet',
              'salty',
              'floral',
            ],
        }
      - { label: 'Category', name: 'category', widget: 'select', options: ['general', 'review', 'group tasting'], default: 'review' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
